version: '3.3'
      
networks:
  frontend:
    external: true
  autheliaBridge: {}

services:
  authelia:
    image: authelia/authelia
    container_name: authelia
    volumes:
      - /docker-data/authelia/authelia-config:/config
      - /docker-data/authelia/secrets:/secrets
    networks:
      - frontend
      - autheliaBridge
    ports:
      - 9091:9091
    restart: unless-stopped
    environment:
      - AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE=/secrets/SMTP_PASSWORD
      - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/secrets/ENCRYPTION_KEY
      - AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE=/secrets/JWT_SECRET
      - AUTHELIA_SESSION_SECRET_FILE=/secrets/SESSION_SECRET
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    labels:
      traefik.enable: 'true'
      traefik.http.routers.authelia.rule: 'Host(`authelia.${DOMAINNAME}`)'
      traefik.http.routers.authelia.entryPoints: 'websecure'
      traefik.http.routers.authelia.tls: 'true'
      traefik.http.routers.authelia.tls.certresolver: 'cloudflare'
      traefik.http.routers.authelia.service: authelia-svc
      traefik.http.services.authelia-svc.loadbalancer.server.port: 9091
      traefik.http.middlewares.authelia.forwardAuth.address: 'http://authelia:9091/api/authz/forward-auth'
      traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader: 'true'
      traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders: 'Remote-User,Remote-Groups,Remote-Email,Remote-Name'

  redis:
    image: redis:alpine
    container_name: redis_authelia
    networks:
      - autheliaBridge
    volumes:
      - /docker-data/authelia/redis-data:/data
    expose:
      - 6379
    restart: unless-stopped
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000