services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - APP_URL=https://${DOMAINNAME}
    volumes:
      - /docker-data/heimdall:/config
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.heimdall.rule: Host(`${DOMAINNAME}`)
      traefik.http.routers.heimdall.entrypoints: websecure
      traefik.http.routers.heimdall.tls: true
      traefik.http.routers.heimdall.tls.certresolver: cloudflare
      traefik.http.routers.heimdall.middlewares: authelia@docker
    networks:
      - frontend
networks:
  frontend:
    external: true
